(() => {
  "use strict";
  const D = window.SW_V8;
  const app = document.getElementById("app");
  const candidateSheet = "assets/v7-journey/nail-file-candidates.png";
  const revisionB1 = "assets/v8-journey/nail-file-revision-b1.png";
  const keyframeImage = "assets/v7-journey/empty-cinema-keyframe.png";
  const initial = () => ({
    screen:"library", theme:"light", intakeType:"idea", intakeStep:0, source:D.sources.idea,
    rights:false, sensitive:false, duplicate:false, parseFailed:false, splitConfirmed:false, scriptMode:"direct", assignment:null,
    episode:"EP01", route:"screenplay", scene:"EP01-SC02", edit:false, draft:D.scenes[1].body,
    dirty:false, saveFailed:false, conflict:false, drawer:null, taskPhase:0, taskSkill:"short-drama-write",
    ep3Rejected:false, ep3Revised:false, staleChoice:null, visualGenerated:false, selected:"",
    imageRevision:false, acceptedSource:"", refAccepted:false, refReplaced:false, keyframe:false,
    videoState:"idle", notice:"", modal:null, freshProject:false, onboarding:null, archived:true
  });
  let s = initial();
  let noticeTimer;
  const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
  const pill = (text, tone="") => `<span class="pill ${tone}">${esc(text)}</span>`;
  const ep = () => D.episodes.find(x => x.id === s.episode);
  const notify = text => { s.notice=text; render(); clearTimeout(noticeTimer); noticeTimer=setTimeout(()=>{s.notice="";render()},2400); };

  function topbar() {
    return `<header class="topbar"><button class="brand" data-action="library"><span class="brand-mark">场</span><span><b>Script Weaver</b><small>Creator Journey Workbench · V8</small></span></button>${s.screen==="workbench"?`<nav class="crumb"><button data-action="library">项目库</button><i>/</i><span>十一秒</span><i>/</i><b>${s.episode}</b></nav>`:""}<div class="top-actions"><button class="quiet" data-action="tasks">后台任务 <span class="count">3</span></button><button class="quiet" data-action="theme" aria-label="切换明暗主题">${s.theme==="light"?"暗色":"亮色"}</button>${s.screen==="workbench"?`<button class="primary" data-action="new-input">新的输入</button>`:""}</div></header>`;
  }

  function library() {
    return `<main class="library" data-screen-label="项目库"><header class="library-head"><div><span class="eyebrow">Your story slate</span><h1>作品不是流水线，<br>从上次的决定继续。</h1></div><button class="primary big" data-action="new-project">＋ 新建作品</button></header><section class="project-grid"><article class="project-card featured"><div class="project-top"><span class="kicker">8 集竖屏短剧</span>${pill("3 个后台任务","info")}</div><h2>十一秒</h2><p>给予、控制与第一次拒绝。最近停在 EP01 的指甲锉视觉参考。</p><div class="resume"><span><small>上次位置</small><b>EP01 · 视觉事实 · PROP-001</b></span><button class="primary" data-action="resume">继续创作 →</button></div><div class="project-flags">${pill("1 个未保存草稿","warn")}${pill("EP03 待审 ChangeSet","info")}${pill("EP04 · 3 项 stale","bad")}</div></article><article class="project-card"><span class="kicker">${s.archived?"归档 · 单集":"已恢复 · 单集"}</span><h2>海面以下</h2><p>最后停在剧本 v3。没有后台任务。</p><button class="secondary" data-action="${s.archived?'restore-project':'notice'}" ${s.archived?'':'data-message="项目已经在项目库中"'}>${s.archived?"恢复项目":"已恢复"}</button></article><button class="project-card empty-project" data-action="new-project"><span>＋</span><b>开始下一个故事</b><small>idea、原著或现成剧本都可以</small></button></section><section class="library-ledger"><header><span class="eyebrow">Needs attention</span><b>跨项目也不会丢失的工作</b></header><div><span>EP03 剧本 v2 等待创作审批</span>${pill("submitted","info")}<button data-action="resume-ep3">打开</button></div><div><span>EP06 写作任务失败；accepted 事实未改变</span>${pill("failed","bad")}<button data-action="tasks">查看</button></div></section></main>`;
  }

  const intakeKinds = [
    ["idea","一个故事想法","发展人物、冲突与八集结构"],
    ["novel","原著或长篇材料","先确认权利，再按需做原著分析"],
    ["single","一集现成剧本","直接接受，或让 Codex 规范化"],
    ["multi","多集完整剧本","确认分集切分，再逐集建立版本"]
  ];
  function intake() {
    if (!s.intakeStep) return `<main class="intake" data-screen-label="四类创作入口"><header><button class="back" data-action="library">← 项目库</button><span class="eyebrow">New project</span><h1>你现在手里有什么？</h1><p>入口只决定第一步，不限制作品以后怎么发展。</p></header><div class="intake-grid">${intakeKinds.map(([id,title,copy],i)=>`<button class="intake-card" data-action="choose-intake" data-id="${id}"><span>0${i+1}</span><h2>${title}</h2><p>${copy}</p><b>开始 →</b></button>`).join("")}</div></main>`;
    const novel=s.intakeType==="novel", single=s.intakeType==="single", multi=s.intakeType==="multi", assigned=s.intakeType==="assignment";
    const title=assigned?(s.assignment==="supplement"?"添加当前故事的补充材料":`添加 ${s.episode} 的修订依据`):intakeKinds.find(x=>x[0]===s.intakeType)[1];
    const sourceLabel=assigned?(s.assignment==="supplement"?"补充材料":"本集修订依据"):novel?"原著正文或文件":single?"单集剧本":multi?"多集整稿":"故事想法";
    return `<main class="intake form" data-screen-label="${s.intakeType} 输入快照"><header><button class="back" data-action="back-intake">← ${assigned?"返回工作台":"更换入口"}</button><span class="eyebrow">Immutable source snapshot</span><h1>${title}</h1><p>${assigned?"本次输入先成为 source candidate，不会直接覆盖 accepted 事实。":"创建后原始输入保持不变；后续修改只产生候选版本。"}</p></header><section class="form-sheet">${assigned?`<section class="split-preview"><header><b>${s.assignment==="supplement"?"绑定当前项目":"绑定当前集与 revision"}</b>${pill(s.assignment==="supplement"?"development 保持 accepted":`${s.episode} · revision 18`,"info")}</header><p>${s.assignment==="supplement"?"提交后进入项目材料候选区。":"提交后可创建范围化 short-drama-write Task。"}</p></section>`:`<label>项目名<input id="projectName" value="十一秒"></label>`}<label>${sourceLabel}<textarea id="sourceText">${esc(s.source)}</textarea></label>${!single&&!multi&&!assigned?`<div class="form-row"><label>目标集数<input value="8 集"></label><label>单集时长<input value="约 2 分钟"></label></div>`:""}${novel?`<div class="confirm-list"><label><input type="checkbox" data-field="rights" ${s.rights?"checked":""}> 我确认拥有本次改编所需的使用权</label><label><input type="checkbox" data-field="sensitive" ${s.sensitive?"checked":""}> 我已检查现实人物、隐私和敏感内容</label></div>${s.duplicate?`<div class="inline-error">发现同来源快照。可以取消，或明确作为补充材料导入。</div>`:""}${s.parseFailed?`<div class="inline-error"><b>解析失败</b> · 没有创建项目。请粘贴正文或更换文件。 <button data-action="retry-parse">重试</button></div>`:""}`:""}${single?`<fieldset><legend>如何开始</legend><label><input type="radio" name="scriptMode" value="direct" ${s.scriptMode==='direct'?'checked':''}> 直接作为 screenplay v1 提交整体审批</label><label><input type="radio" name="scriptMode" value="revise" ${s.scriptMode==='revise'?'checked':''}> 创建 short-drama-write 修订任务</label></fieldset>`:""}${multi?`<section class="split-preview"><header><b>识别到 8 集边界</b>${pill(s.splitConfirmed?"已确认":"待确认",s.splitConfirmed?"good":"warn")}</header><p>EP01 “未通过的好友申请” → EP08 “十一秒”</p><button class="secondary" data-action="confirm-split">${s.splitConfirmed?"切分已确认":"检查并确认分集切分"}</button></section>`:""}<div class="form-actions"><button class="secondary" data-action="cancel-intake">取消且不写入</button>${novel?`<button class="quiet" data-action="simulate-duplicate">模拟重复</button><button class="quiet" data-action="simulate-parse">模拟解析失败</button>`:""}<button class="primary" data-action="create-from-intake" ${(novel&&(!s.rights||!s.sensitive||s.parseFailed))||(multi&&!s.splitConfirmed)||!s.source.trim()?"disabled":""}>${assigned?"保存 source candidate →":"冻结输入并创建项目 →"}</button></div></section></main>`;
  }

  function episodeRail() {
    return `<aside class="episode-rail"><button class="season-link ${s.route==="season"?"active":""}" data-action="route" data-route="season"><span>全季</span><small>8 集 · 3 项待处理</small></button><div class="episode-list">${D.episodes.map(e=>`<button class="episode-link ${s.episode===e.id?"active":""}" data-action="episode" data-id="${e.id}"><span><b>${e.id}</b><small>${e.title}</small></span><i class="state-mark ${e.freshness==='stale'?'stale':e.state}" aria-label="${e.state} ${e.freshness}">${e.freshness==='stale'?'!':e.state==='accepted'?'✓':e.state==='submitted'?'↥':'·'}</i></button>`).join("")}</div><button class="season-link" data-action="batch"><span>批量任务</span><small>4 个独立 Task</small></button></aside>`;
  }

  function contextRail() {
    const scenes=s.episode==="EP01"?D.scenes:[];
    return `<aside class="context-rail"><div class="episode-title"><span class="eyebrow">${s.episode}</span><h2>${ep().title}</h2><p>${ep().note}</p></div><nav class="projection-nav">${[["screenplay","剧本"],["visual","视觉事实"],["storyboard","分镜"],["motion","视频提示词"],["package","生产包"]].map(([id,x])=>`<button class="${s.route===id?'active':''}" data-action="route" data-route="${id}"><span>${x}</span><small>${id==='screenplay'?'v1 正式':id==='visual'?'3 个事实':id==='storyboard'?'4 镜头':id==='motion'?'1 待生成':'未交付'}</small></button>`).join("")}</nav>${s.route==="screenplay"?`<div class="scene-list"><span class="eyebrow">Scenes</span>${scenes.length?scenes.map(x=>`<button class="${s.scene===x.id?'active':''}" data-action="scene" data-id="${x.id}"><b>${x.id.replace('EP01-','')}</b><small>${x.heading}</small></button>`).join(""):`<div class="empty-small">尚未拆场。先创建写作任务，或手工开始。</div>`}</div>`:""}<div class="rail-footer"><button class="quiet" data-action="development">故事开发文档 v2</button><small>包含分集地图 · 整份审批</small></div></aside>`;
  }

  function workspaceHeader(title,meta,actions="") {
    return `<header class="workspace-head"><div><span class="eyebrow">${esc(meta)}</span><h1>${esc(title)}</h1></div><div class="head-actions">${actions}</div></header>`;
  }
  function seasonView() {
    if(s.freshProject&&(s.onboarding==="development-task"||s.onboarding==="development-review")) return `<section class="canvas season" data-screen-label="新项目开发闸门"><div class="empty-state"><span>FRESH PROJECT · SOURCE ACCEPTED</span><h1>先确认故事开发文档</h1><p>目前只有不可变 source snapshot。剧本、视觉事实和分镜尚未解锁；ChangeSet 应用后仍需整体接受开发文档。</p>${s.onboarding==='development-review'?`<button class="primary" data-action="development">审阅故事开发文档候选</button>`:''}</div></section>`;
    if(s.freshProject&&s.onboarding==="multi-draft") return `<section class="canvas season" data-screen-label="新导入多集草稿"><div class="empty-state"><span>MULTI-EPISODE IMPORT</span><h1>8 集边界已确认，剧本尚未接受</h1><p>切分确认只建立八份 draft / submitted 候选，不等于任何一集已经成为正式剧本。</p><button class="primary" data-action="episode" data-id="EP01">从 EP01 开始整体审批</button></div></section>`;
    return `<section class="canvas season" data-screen-label="八集全季视图">${workspaceHeader("十一秒 · 全季","8 episodes · 目标 2 分钟 / 集",`<button class="secondary" data-action="development">打开故事开发文档</button>`)}<div class="season-summary"><div><small>当前正式开发文档</small><b>v2 · accepted + current</b></div><div><small>全季完成度</small><b>35%</b></div><div><small>需创作者处理</small><b>EP03、EP04、EP06</b></div></div><div class="episode-table">${D.episodes.map(e=>`<button data-action="episode" data-id="${e.id}"><span><b>${e.id}</b><small>${e.title}</small></span><span>${e.scene}</span><span><i style="--p:${e.progress}%"></i>${e.progress}%</span><span>${pill(e.state,e.state==='accepted'?'good':e.state==='submitted'?'info':'')}${e.freshness==='stale'?pill('stale','bad'):''}</span></button>`).join("")}</div><section class="continuity"><header><span class="eyebrow">Cross-episode continuity</span><b>全局身份，分集只引用变体和状态</b></header>${D.assets.map(a=>`<div><span><b>${a.id} · ${a.name}</b><small>${a.kind}</small></span><span>${a.variant}</span><span>${a.range}</span><small>${a.flow}</small></div>`).join("")}</section></section>`;
  }

  function screenplayView() {
    if(s.freshProject&&s.onboarding==="multi-draft") return `<section class="canvas screenplay" data-screen-label="多集导入逐集审批">${workspaceHeader(`${s.episode} · 导入候选`,"episode boundary confirmed · screenplay not accepted",pill("submitted","info"))}<article class="paper"><header class="scene-heading"><b>IMPORTED DRAFT</b><span>切分确认没有赋予正式版本状态</span></header><div class="script-copy"><p>${s.episode} 的导入正文将在这里按整份剧本审批。</p></div></article><footer class="canvas-actions"><button class="danger" data-action="notice" data-message="本集候选已退回；其他集状态不变">退回本集</button><button class="primary" data-action="accept-screenplay">整体接受本集 screenplay</button></footer></section>`;
    if(s.freshProject&&s.onboarding==="screenplay-review") return `<section class="canvas screenplay" data-screen-label="新导入剧本整体审批">${workspaceHeader("EP01 · 导入剧本","screenplay candidate v1",pill("submitted","info"))}<article class="paper"><header class="scene-heading"><b>SOURCE SNAPSHOT</b><span>${s.scriptMode==='direct'?"原文直接进入审批":"Codex 修订 ChangeSet 已应用"}</span></header><div class="script-copy">${esc(s.source).split("\n").map(x=>x?`<p>${x}</p>`:`<br>`).join("")}</div></article><footer class="canvas-actions"><button class="danger" data-action="notice" data-message="已退回整份 screenplay v1；source snapshot 保持不变">退回整份</button><button class="primary" data-action="accept-screenplay">整体接受 screenplay v1</button></footer></section>`;
    if (s.episode==="EP03") return ep3View();
    if (s.episode==="EP04") return ep4View();
    if (s.episode!=="EP01") return `<section class="canvas"><div class="empty-state"><span>${s.episode}</span><h1>${ep().title}</h1><p>${ep().note}。你可以手工开始，或创建范围化 Codex Task。</p><button class="primary" data-action="open-task">创建 short-drama-write Task</button></div></section>`;
    const scene=D.scenes.find(x=>x.id===s.scene)||D.scenes[1];
    return `<section class="canvas screenplay" data-screen-label="可编辑单集剧本">${workspaceHeader(ep().title,`${s.episode} · screenplay`,`${pill("v1 正式","good")}${s.dirty?pill("未保存","warn"):pill("已保存","good")}<button class="secondary" data-action="history">版本</button>`)}<article class="paper">${s.edit?`<label class="editor-label">${scene.id} · ${scene.heading}<textarea id="scriptEditor">${esc(s.draft)}</textarea></label>`:`<header class="scene-heading"><b>${scene.id}</b><span>${scene.heading}</span></header><div class="script-copy">${esc(scene.body).split("\n").map(x=>x?`<p>${x}</p>`:`<br>`).join("")}</div>`}</article><footer class="canvas-actions"><div>${s.edit?`<button class="secondary" data-action="discard">放弃修改</button><button class="secondary" data-action="codex-selection">让 Codex 修改此场</button>`:`<button class="secondary" data-action="edit-script">编辑此场</button><button class="secondary" data-action="codex-selection">选择范围交给 Codex</button>`}</div>${s.edit?`<button class="primary" data-action="save-draft">保存 draft</button>`:`<button class="primary" data-action="submit-script">提交剧本候选</button>`}</footer>${s.saveFailed?`<div class="blocking-banner"><b>保存失败</b><span>内容仍保留在编辑器中，没有切换页面。</span><button data-action="retry-save">重试保存</button></div>`:""}${s.conflict?`<div class="blocking-banner"><b>revision 冲突</b><span>本地草稿基于 v1；项目已有 v2。比较后再创建新候选。</span><button data-action="resolve-conflict">比较版本</button></div>`:""}</section>`;
  }
  function ep3View(){return `<section class="canvas" data-screen-label="EP03 拒绝修订闭环">${workspaceHeader(ep().title,"EP03 · screenplay decision",`${pill(s.ep3Revised?"candidate v3":"candidate v2","info")}`)}<article class="paper diff-paper"><div class="diff-line old">周屿终于明白，沈禾只是想要一个道歉。</div><div class="diff-line new">指甲锉在桌面停住。沈禾没有要道歉，只问：四十页报告里，有一页写过我吗？</div><p>Codex 将冲突从“误会解除”改成“叙述者仍用成果替代倾听”。</p></article><footer class="canvas-actions"><button class="secondary" data-action="open-task">查看 ChangeSet 与来源</button><div>${!s.ep3Rejected?`<button class="danger" data-action="reject-ep3">退回并说明</button><button class="primary" data-action="accept-ep3">整体接受 v2</button>`:s.ep3Revised?`<button class="primary" data-action="accept-ep3">整体接受 v3</button>`:`<button class="primary" data-action="revise-ep3">基于反馈创建新 Task</button>`}</div></footer>${s.ep3Rejected?`<div class="feedback-note"><b>v2 已拒绝</b><span>反馈：不要让主角在这一集完成自我解释；让指甲锉继续承担没有说出口的话。</span></div>`:""}</section>`}
  function ep4View(){return `<section class="canvas" data-screen-label="EP04 stale 影响处理">${workspaceHeader(ep().title,"EP04 · accepted v1",`${pill("accepted","good")}${pill("stale","bad")}`)}<article class="impact-sheet"><span class="eyebrow">Upstream changed</span><h2>故事开发文档 v3 候选改变了 EP04 的职责</h2><p>“黑胶带封住阳光”不再是浪漫姿态，而是周屿替沈禾决定她应该看见什么。现有剧本仍是 accepted 历史，没有被覆盖。</p><div class="impact-list"><span>EP04 screenplay v1</span><b>accepted + stale</b><span>REF-LOC-004-v1</span><b>accepted + stale</b><span>SHOT-017 / KF-017</span><b>inputs changed</b></div></article><footer class="canvas-actions"><button class="secondary" data-action="stale-choice" data-choice="keep">继续使用旧事实</button><button class="secondary" data-action="stale-choice" data-choice="later">稍后处理</button><button class="primary" data-action="stale-choice" data-choice="revise">按新上游创建修订 Task</button></footer>${s.staleChoice?`<div class="feedback-note"><b>已选择：${s.staleChoice==='keep'?'继续使用':s.staleChoice==='later'?'稍后处理':'创建修订'}</b><span>系统没有自动重写任何下游事实。</span></div>`:""}</section>`}

  function visualView() {
    return `<section class="canvas visual" data-screen-label="视觉候选到正式 REF">${workspaceHeader("视觉事实与参考图","EP01 · global asset identity",`${pill("screenplay v1","good")}`)}<div class="asset-strip">${D.assets.map(a=>`<button class="asset-card ${a.id==='PROP-001'?'active':''}" data-action="notice" data-message="人物、地点和道具复用同一候选面板"><small>${a.kind}</small><b>${a.id} · ${a.name}</b><span>${a.variant}</span><i>${a.range}</i></button>`).join("")}</div><article class="visual-decision"><header><div><span class="eyebrow">PROP-001 · PSTATE-001-B</span><h2>指甲锉 · 边缘磨钝</h2><p>全局 identity；当前状态在 EP01–EP03 生效。进入：沈禾右手持有；离开：放回深色外套。</p></div>${s.refAccepted?`${pill(s.refReplaced?"REF-PROP-001-v2":"REF-PROP-001-v1","good")}`:pill("尚无正式 REF","warn")}</header>${!s.visualGenerated?`<div class="visual-empty"><span>视觉事实不是图片</span><p>Codex 生成的图片先成为 candidate media。应用 ChangeSet 也不会自动接受为正式 REF。</p><button class="primary" data-action="generate-visual">让 Codex 生成 3 张候选</button></div>`:`<div class="candidate-grid">${D.candidates.map(c=>`<button class="candidate ${s.selected===c.id?'selected':''}" data-action="select-candidate" data-id="${c.id}"><img src="${candidateSheet}" alt="指甲锉候选 ${c.id}" class="crop-${c.crop}"><span><b>候选 ${c.id}</b><small>${c.asset} · ${c.prompt}</small></span></button>`).join("")}</div>${s.selected?`<section class="candidate-detail">${s.imageRevision?`<img src="${revisionB1}" alt="候选 B 的局部编辑版本 B1"><div><span class="eyebrow">Candidate B1 · derived from B</span><h3>保留细齿，削弱表面划痕</h3><p>新候选，没有覆盖 B，也还不是正式 REF。</p></div>`:`<div><span class="eyebrow">Candidate ${s.selected} selected</span><h3>继续局部编辑，或接受当前候选</h3><textarea id="imagePrompt">保留哑光细齿，削弱表面划痕，让边缘看起来被长期磨钝。</textarea></div>`}<div class="candidate-actions"><button class="secondary" data-action="revise-image">继续局部编辑</button><button class="primary" data-action="accept-ref">${s.refAccepted?"替换正式 REF":"接受为正式 REF"}</button></div></section>`:""}`}${s.refAccepted?`<section class="lineage"><div><small>Candidate lineage</small><b>B → B1 → ${s.refReplaced?'REF-PROP-001-v2':'REF-PROP-001-v1'}</b></div><div><small>下游引用</small><b>SHOT-004 · KF-004 · MOTION-004</b></div>${s.refReplaced?`<div class="stale-callout"><b>旧 REF 保留历史</b><span>SHOT-004、KF-004、MOTION-004 与旧媒体已标记 stale；没有自动重生成。</span></div>`:""}</section>`:""}</article><footer class="canvas-actions"><button class="secondary" data-action="variant-choice">沿用 / 新变体 / 暂不解决</button><button class="primary" data-action="route" data-route="storyboard" ${s.refAccepted?"":"disabled"}>在分镜中使用 REF →</button></footer></section>`;
  }

  function storyboardView(){return `<section class="canvas" data-screen-label="分镜与冻结关键帧">${workspaceHeader("SHOT-004 · 磨到不刮人为止","EP01-SC02 · 6 秒",`${pill(s.refAccepted?"正式 REF 已绑定":"缺少 REF",s.refAccepted?"good":"warn")}`)}<article class="shot-sheet"><div><span class="eyebrow">Dramatic duty</span><h2>让沈禾的克制与周屿的计算第一次同时出现。</h2><dl><dt>起点</dt><dd>沈禾坐在第七排，右手持 PROP-001；周屿在后景失焦。</dd><dt>终点</dt><dd>指甲锉停在指尖上方，沈禾抬眼但不转头。</dd><dt>连续性</dt><dd>引用 ${s.refReplaced?'REF-PROP-001-v2':'REF-PROP-001-v1'} · PSTATE-001-B。</dd></dl></div>${s.keyframe?`<figure><img src="${keyframeImage}" alt="空影院中沈禾使用指甲锉的 SHOT-004 冻结关键帧"><figcaption>KF-004 · frozen · Codex image candidate accepted</figcaption></figure>`:`<div class="keyframe-empty"><span>KF-004</span><p>冻结镜头起点，供视频执行端稳定引用。</p><button class="primary" data-action="keyframe">让 Codex 生成冻结关键帧</button></div>`}</article><footer class="canvas-actions"><button class="secondary" data-action="route" data-route="visual">返回 REF</button><button class="primary" data-action="route" data-route="motion" ${s.keyframe?"":"disabled"}>编写视频提示词 →</button></footer></section>`}
  function motionView(){return `<section class="canvas" data-screen-label="视频提示词与执行端">${workspaceHeader("MOTION-004 · 视频提示词","Codex prepares · video service renders",`${pill("H3 计划执行端","info")}`)}<article class="motion-sheet"><div class="prompt"><span class="eyebrow">6 秒 · 9:16 · Ref2Video</span><p>从 KF-004 开始。沈禾低头，用指甲锉轻缓磨过右手食指边缘，两次短促动作后停住。她不看周屿，只说“磨到不刮人为止”。镜头极慢向手部推进，银幕冷光稳定。终点：指甲锉停在指尖上方，沈禾抬眼但不转头。</p></div><aside><b>Codex 已准备</b><span>冻结关键帧 KF-004</span><span>正式参考 REF-PROP-001-v1</span><span>动作、表演、运镜、起止状态</span><hr><b>视频成片由执行端生成</b><span>本地 MiniMax H3 · 计划接入</span><span>当前原型未真实连接模型</span></aside></article><footer class="canvas-actions"><button class="secondary" data-action="notice" data-message="输入已冻结；原型没有调用真实 H3">冻结输入预览</button><button class="primary" data-action="run-video">${s.videoState==='candidate'?'查看候选视频':'发送到计划中的本地 H3'}</button></footer>${s.videoState==='candidate'?`<div class="video-result"><div>▶</div><span><b>SHOT-004-h3-01.mp4</b><small>候选视频 · 不自动成为正式媒体</small></span></div>`:""}</section>`}

  function packageView(){return `<section class="canvas" data-screen-label="交付本轮生产包">${workspaceHeader("交付本轮生产包","versioned production package",pill("不是最终成片","warn"))}<article class="package"><header><div><span class="eyebrow">PACKAGE-2026-08-30-v1</span><h2>EP01 · 可交付</h2></div><b>12 / 15 项</b></header><div class="package-groups"><section><h3>Accepted facts</h3><p>故事开发文档 v2</p><p>EP01 screenplay v1</p><p>3 个视觉事实 / 1 个正式 REF</p><p>4 个分镜 / 1 个冻结关键帧</p></section><section><h3>Production inputs</h3><p>MOTION-004 视频提示词</p><p>SHOT-004-h3-01 候选媒体</p><p>来源与版本 provenance manifest</p></section><section class="issues"><h3>Missing / failed / stale / excluded</h3><p>Missing · SHOT-005 冻结关键帧</p><p>Failed · EP06 写作 Task</p><p>Stale · EP04 下游 3 项</p><p>Excluded · 未接受图片候选 A / C</p></section></div><div class="not-included"><b>本生产包不包含</b><span>最终剪辑、配音、音乐、字幕、混音、发行和完整视频成片。</span></div></article><footer class="canvas-actions"><button class="secondary" data-action="route" data-route="season">返回全季</button><button class="primary" data-action="deliver">交付本轮生产包</button></footer></section>`}

  function developmentModal(){return `<div class="overlay"><section class="sheet development" role="dialog" aria-modal="true" aria-labelledby="development-title"><header><div><span class="eyebrow">Development document · whole-version approval</span><h2 id="development-title">故事开发文档 v2</h2></div><button class="quiet" data-action="close-modal">关闭</button></header><div class="development-body">${D.development.map(([t,c],i)=>`<section><span>0${i+1}</span><div><h3>${t}</h3><p>${c}</p>${t==='分集地图'?`<small>分集地图属于本版本；没有独立“接受分集地图”。调整它会创建整份开发文档新候选。</small>`:''}</div></section>`).join("")}</div><footer><button class="secondary" data-action="restore-version">从 v1 创建恢复候选</button><button class="danger" data-action="notice" data-message="已退回整份开发文档；反馈将进入下一次 Task">退回整份</button><button class="primary" data-action="accept-development">整体接受 v2</button></footer></section></div>`}
  function taskDrawer(){const steps=[["创建范围化 Task","pinned project / episode / revision"],["Codex claim → running","CLI 读取 pinned Skill 与 context"],["ChangeSet submitted","检查 operations、来源与影响"],["应用 ChangeSet","候选进入项目；正式事实仍不变"],["创作审批","接受或退回完整候选"]];return `<aside class="decision-drawer" role="dialog" aria-modal="true" aria-labelledby="task-title"><header><div><span class="eyebrow">CLI-first handoff</span><h2 id="task-title">${s.episode} · ${s.taskSkill}</h2></div><button class="quiet" data-action="close-drawer">关闭</button></header><div class="task-ident"><span>TASK-${s.episode}-07</span><span>RUN-02</span><span>source revision 18</span></div><ol>${steps.map((x,i)=>`<li class="${i<s.taskPhase?'done':i===s.taskPhase?'active':''}"><i>${i<s.taskPhase?'✓':i+1}</i><span><b>${x[0]}</b><small>${x[1]}</small></span></li>`).join("")}</ol>${s.taskPhase===2?`<div class="ops"><b>3 operations</b><code>document.version.create · ${s.episode}</code><code>source: accepted upstream</code><code>impact: candidate only</code></div>`:''}<div class="drawer-note">应用结构化修改 ≠ 接受创作结果。Codex 不能直接批准版本或登记正式 REF。</div><footer><button class="secondary" data-action="task-fail">模拟失败</button><button class="primary" data-action="task-next">${["复制 context 并模拟 claim","模拟提交 ChangeSet","审阅后应用 ChangeSet","进入创作审批","完成"][s.taskPhase]||"完成"}</button></footer></aside>`}
  function batchDrawer(){return `<aside class="decision-drawer" role="dialog" aria-modal="true" aria-labelledby="batch-title"><header><div><span class="eyebrow">Task Group · TG-WRITE-02</span><h2 id="batch-title">EP05–EP08 批量写作</h2></div><button class="quiet" data-action="close-drawer">关闭</button></header><div class="batch-list">${D.batch.map(([name,state],i)=>`<div><span><b>${name}</b><small>独立输入 revision · 独立 AgentRun</small></span>${pill(state,state==='failed'?'bad':state==='succeeded'?'good':'info')}${state==='failed'?`<button data-action="retry-batch">单独重试</button>`:''}</div>`).join("")}</div><div class="drawer-note">部分失败不会回滚已成功任务；重试创建新 AgentRun，不改写旧运行记录。</div></aside>`}
  function statusDrawer(){return `<aside class="decision-drawer wide" role="dialog" aria-modal="true" aria-labelledby="status-title"><header><div><span class="eyebrow">Background ledger</span><h2 id="status-title">三轴状态，不用一个颜色混在一起</h2></div><button class="quiet" data-action="close-drawer">关闭</button></header><div class="status-table"><div class="status-head"><span>对象</span><span>审批</span><span>新鲜度</span><span>执行</span></div>${D.statusFixtures.map(r=>`<div><b>${r[0]}</b>${pill(r[1],r[1]==='accepted'?'good':r[1]==='submitted'?'info':'')}${pill(r[2],r[2]==='stale'?'bad':'')}${pill(r[3],r[3]==='failed'||r[3]==='inputs-changed'?'bad':r[3]==='succeeded'?'good':'info')}</div>`).join("")}</div><div class="drawer-note"><b>失败不破坏事实：</b>EP06 Task failed，但上一版 accepted 开发文档和其他集剧本保持不变。</div></aside>`}

  function completionModal(){return `<div class="overlay"><section class="sheet completion" role="dialog" aria-modal="true" aria-labelledby="completion-title"><span class="eyebrow">Production package delivered</span><h2 id="completion-title">这轮工作已经留下清楚的版本边界。</h2><p>你可以继续这个作品，也可以开始下一次输入。任何选择都不会静默覆盖当前事实。</p><div class="next-grid"><button data-action="next-episode"><b>开始下一集</b><small>去 EP02 的未完成工作</small></button><button data-action="next-season"><b>创建下一季</b><small>继承世界与全局资产 identity</small></button><button data-action="new-project"><b>创建全新作品</b><small>从 idea、原著或剧本开始</small></button><button data-action="library"><b>返回项目库</b><small>稍后恢复当前创作位置</small></button></div></section></div>`}
  function unsavedModal(){return `<div class="overlay"><section class="sheet compact" role="dialog" aria-modal="true" aria-labelledby="unsaved-title"><span class="eyebrow">Unsaved draft</span><h2 id="unsaved-title">先处理当前场的修改</h2><p>切换集数不会自动保存或丢弃内容。</p><footer><button class="secondary" data-action="cancel-switch">取消</button><button class="danger" data-action="discard-switch">放弃并切换</button><button class="primary" data-action="save-switch">保存后切换</button></footer></section></div>`}
  function variantModal(){return `<div class="overlay"><section class="sheet compact" role="dialog" aria-modal="true" aria-labelledby="variant-title"><span class="eyebrow">Cross-episode variant</span><h2 id="variant-title">EP04 需要不同的道具状态吗？</h2><div class="next-grid"><button data-action="close-modal"><b>沿用 PSTATE-001-B</b><small>扩展有效范围到 EP04</small></button><button data-action="close-modal"><b>创建 PSTATE-001-C</b><small>保留 identity，新建状态变体</small></button><button data-action="close-modal"><b>暂不解决</b><small>记录连续性 blocker</small></button></div></section></div>`}
  function newInputModal(){return `<div class="overlay"><section class="sheet compact" role="dialog" aria-modal="true" aria-labelledby="new-input-title"><span class="eyebrow">New input</span><h2 id="new-input-title">这次输入属于哪里？</h2><p>先确定归属，再创建不可变 source 快照。</p><div class="next-grid"><button data-action="assign-input" data-assignment="supplement"><b>当前故事的补充材料</b><small>不直接覆盖 accepted 事实</small></button><button data-action="assign-input" data-assignment="revision"><b>某一集的修订依据</b><small>绑定项目、集数与 revision</small></button><button data-action="next-season"><b>下一季起点</b><small>继承资产 identity</small></button><button data-action="new-project"><b>全新作品</b><small>返回四类入口</small></button></div><button class="quiet full" data-action="close-modal">取消</button></section></div>`}

  function workbench(){let body=s.route==="season"?seasonView():s.route==="screenplay"?screenplayView():s.route==="visual"?visualView():s.route==="storyboard"?storyboardView():s.route==="motion"?motionView():packageView();return `<main class="workbench">${episodeRail()}${contextRail()}<div class="workspace">${body}</div>${s.drawer==='task'?taskDrawer():s.drawer==='batch'?batchDrawer():s.drawer==='status'?statusDrawer():''}</main>`}
  function render(){
    document.documentElement.dataset.theme=s.theme;
    const main=s.screen==="library"?library():s.screen==="intake"?intake():workbench();
    app.innerHTML=`<div class="shell">${topbar()}${main}${s.modal==='development'?developmentModal():s.modal==='complete'?completionModal():s.modal==='unsaved'?unsavedModal():s.modal==='variant'?variantModal():s.modal==='new-input'?newInputModal():''}${s.notice?`<div class="notice" role="status">${esc(s.notice)}</div>`:''}<button class="reset" data-action="reset">重置演示数据</button></div>`;
    if(s.freshProject&&s.onboarding?.startsWith('development'))document.querySelectorAll('.projection-nav button,.episode-link').forEach(x=>{x.disabled=true;x.setAttribute('aria-disabled','true');});
    if(s.freshProject&&s.onboarding?.startsWith('screenplay'))document.querySelectorAll('.projection-nav button:not([data-route="screenplay"]),.episode-link').forEach(x=>{x.disabled=true;x.setAttribute('aria-disabled','true');});
    const lineage=document.querySelector('.lineage>div:first-child b');
    if(lineage&&s.acceptedSource){const chain=s.acceptedSource.endsWith('1')?`${s.acceptedSource.slice(0,-1)} → ${s.acceptedSource}`:s.acceptedSource;lineage.textContent=`${chain} → ${s.refReplaced?'REF-PROP-001-v2':'REF-PROP-001-v1'}`;}
    const panel=document.querySelector('.overlay .sheet,.decision-drawer');
    if(panel)requestAnimationFrame(()=>panel.querySelector('button:not([disabled]),input:not([disabled]),textarea:not([disabled])')?.focus());
  }

  function goEpisode(id){if(s.dirty){s.modal='unsaved';s.pendingEpisode=id;render();return;}s.episode=id;s.route='screenplay';s.scene=id==='EP01'?'EP01-SC02':'';render();}
  app.addEventListener("input",e=>{if(e.target.id==='sourceText'){s.source=e.target.value;const submit=document.querySelector('[data-action="create-from-intake"]');if(submit&&s.intakeType==='assignment')submit.disabled=!s.source.trim();}if(e.target.id==='scriptEditor'){s.draft=e.target.value;s.dirty=true;const tag=document.querySelector('.pill.warn');if(tag)tag.textContent='未保存';}});
  app.addEventListener("change",e=>{if(e.target.dataset.field==='rights')s.rights=e.target.checked;if(e.target.dataset.field==='sensitive')s.sensitive=e.target.checked;if(e.target.name==='scriptMode')s.scriptMode=e.target.value;render();});
  app.addEventListener("click",e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
    if(a==='library'){s.screen='library';s.modal=null;s.drawer=null;}
    else if(a==='new-project'){s.screen='intake';s.intakeStep=0;s.modal=null;s.assignment=null;s.freshProject=false;}
    else if(a==='resume'){s.screen='workbench';s.episode='EP01';s.route='visual';}
    else if(a==='resume-ep3'){s.screen='workbench';s.episode='EP03';s.route='screenplay';}
    else if(a==='choose-intake'){s.intakeType=b.dataset.id;s.source=D.sources[s.intakeType];s.intakeStep=1;s.scriptMode='direct';}
    else if(a==='back-intake'){if(s.assignment){s.screen='workbench';s.assignment=null;}else s.intakeStep=0;}
    else if(a==='cancel-intake'){if(s.assignment){s.screen='workbench';s.assignment=null;}else s.screen='library';}
    else if(a==='simulate-duplicate'){s.duplicate=true;notify('发现同来源快照；尚未导入');return;}
    else if(a==='simulate-parse'){s.parseFailed=true;}
    else if(a==='retry-parse'){s.parseFailed=false;notify('解析已恢复；仍需确认权利');return;}
    else if(a==='confirm-split'){s.splitConfirmed=true;}
    else if(a==='create-from-intake'){
      if(s.intakeType==='assignment'){s.screen='workbench';s.route=s.assignment==='revision'?'screenplay':'season';s.drawer=s.assignment==='revision'?'task':null;s.taskPhase=0;s.taskSkill='short-drama-write';const msg=s.assignment==='revision'?`${s.episode} 修订依据已绑定 revision 18；Task 已创建`:'补充材料已保存为 source candidate；accepted development 未改变';s.assignment=null;notify(msg);return;}
      s.screen='workbench';s.episode='EP01';s.freshProject=true;
      if(s.intakeType==='idea'||s.intakeType==='novel'){s.route='season';s.onboarding='development-task';s.taskSkill='short-drama-develop';s.taskPhase=0;s.drawer='task';}
      else if(s.intakeType==='single'){s.route='screenplay';if(s.scriptMode==='revise'){s.onboarding='screenplay-task';s.taskSkill='short-drama-write';s.taskPhase=0;s.drawer='task';}else{s.onboarding='screenplay-review';s.drawer=null;}}
      else{s.route='season';s.onboarding='multi-draft';s.drawer=null;}
      notify('输入快照已冻结；accepted 事实尚未产生');return;
    }
    else if(a==='episode')goEpisode(b.dataset.id);
    else if(a==='route'){s.route=b.dataset.route;}
    else if(a==='scene'){s.scene=b.dataset.id;s.draft=(D.scenes.find(x=>x.id===s.scene)||D.scenes[1]).body;s.edit=false;s.dirty=false;}
    else if(a==='development'){s.modal='development';}
    else if(a==='close-modal'){s.modal=null;}
    else if(a==='edit-script'){s.edit=true;}
    else if(a==='discard'){s.edit=false;s.dirty=false;s.draft=(D.scenes.find(x=>x.id===s.scene)||D.scenes[1]).body;}
    else if(a==='save-draft'){if(!s.saveFailed){s.saveFailed=true;notify('模拟保存失败：草稿仍保留');return;}s.saveFailed=false;s.dirty=false;s.edit=false;notify('draft 已保存；accepted v1 未改变');return;}
    else if(a==='retry-save'){s.saveFailed=false;s.dirty=false;s.edit=false;notify('draft 保存成功');return;}
    else if(a==='submit-script'||a==='codex-selection'||a==='open-task'){s.drawer='task';s.taskPhase=0;}
    else if(a==='close-drawer'){s.drawer=null;}
    else if(a==='task-next'){if(s.taskPhase<4)s.taskPhase++;else{s.drawer=null;if(s.onboarding==='development-task'){s.onboarding='development-review';s.modal='development';}else if(s.onboarding==='screenplay-task')s.onboarding='screenplay-review';notify('ChangeSet 已应用；候选仍等待创作审批');return;}}
    else if(a==='task-fail'){s.drawer=null;notify('Task failed；accepted 事实未改变');return;}
    else if(a==='reject-ep3'){s.ep3Rejected=true;}
    else if(a==='revise-ep3'){s.ep3Revised=true;s.drawer='task';s.taskPhase=0;}
    else if(a==='accept-ep3'){notify(`${s.ep3Revised?'v3':'v2'} 已成为 EP03 正式剧本`);return;}
    else if(a==='stale-choice'){s.staleChoice=b.dataset.choice;}
    else if(a==='generate-visual'){s.visualGenerated=true;notify('3 张 candidate media 已返回；没有正式 REF');return;}
    else if(a==='select-candidate'){s.selected=b.dataset.id;s.imageRevision=false;}
    else if(a==='revise-image'){s.selected='B';s.imageRevision=true;notify('B1 已生成；B 与当前 REF 均未被覆盖');return;}
    else if(a==='accept-ref'){const source=s.imageRevision?`${s.selected}1`:s.selected;if(s.refAccepted&&s.acceptedSource!==source)s.refReplaced=true;s.acceptedSource=source;s.refAccepted=true;notify(s.refReplaced?'REF v2 已登记；精确下游已标 stale':'正式 REF 已登记');return;}
    else if(a==='keyframe'){s.keyframe=true;}
    else if(a==='run-video'){s.videoState='candidate';notify('静态模拟：H3 未真实接通');return;}
    else if(a==='deliver'){s.modal='complete';}
    else if(a==='next-episode'){s.modal=null;s.episode='EP02';s.route='screenplay';}
    else if(a==='next-season'){s.modal=null;notify('已创建“十一秒 · 第二季”候选入口；继承全局 identity');return;}
    else if(a==='new-input'){s.modal='new-input';}
    else if(a==='assign-input'){s.assignment=b.dataset.assignment;s.modal=null;s.screen='intake';s.intakeType='assignment';s.intakeStep=1;s.source='';}
    else if(a==='variant-choice'){s.modal='variant';}
    else if(a==='tasks'){s.screen='workbench';s.drawer='status';}
    else if(a==='batch'){s.drawer='batch';}
    else if(a==='retry-batch'){notify('EP06 新 AgentRun 已排队；旧失败记录保留');return;}
    else if(a==='theme'){s.theme=s.theme==='light'?'dark':'light';}
    else if(a==='history'){s.conflict=true;notify('恢复 v1 会创建恢复候选 v3，不原地改写历史');return;}
    else if(a==='resolve-conflict'){s.conflict=false;notify('已打开本地草稿与项目 v2 的比较视图');return;}
    else if(a==='restore-version'){notify('已从 v1 创建恢复候选 v3；v1 历史未改变');return;}
    else if(a==='accept-development'){s.modal=null;s.onboarding=null;s.route='season';notify('故事开发文档 v2 已整体接受；全季工作已解锁');return;}
    else if(a==='accept-screenplay'){s.onboarding=null;s.freshProject=false;notify('screenplay v1 已整体接受；正式剧本已建立');return;}
    else if(a==='restore-project'){s.archived=false;notify('海面以下已恢复到项目库');return;}
    else if(a==='notice'){notify(b.dataset.message||'已记录');return;}
    else if(a==='reset'){s=initial();}
    else if(a==='cancel-switch'){s.modal=null;delete s.pendingEpisode;}
    else if(a==='discard-switch'){s.dirty=false;s.edit=false;s.modal=null;const id=s.pendingEpisode;delete s.pendingEpisode;goEpisode(id);return;}
    else if(a==='save-switch'){s.dirty=false;s.edit=false;s.modal=null;const id=s.pendingEpisode;delete s.pendingEpisode;notify('draft 已保存，正在切换');setTimeout(()=>goEpisode(id),350);return;}
    render();
  });
  window.addEventListener('keydown',e=>{
    const panel=document.querySelector('.overlay .sheet,.decision-drawer');
    if(e.key==='Escape'&&panel){e.preventDefault();s.modal=null;s.drawer=null;render();return;}
    if(e.key==='Tab'&&panel){const items=[...panel.querySelectorAll('button:not([disabled]),input:not([disabled]),textarea:not([disabled])')].filter(x=>x.offsetParent!==null);if(items.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
    if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();s.taskSkill='short-drama-write';s.drawer='task';render();}
  });
  render();
})();
