PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY, title TEXT NOT NULL, format TEXT NOT NULL, aspect_ratio TEXT NOT NULL, prompt_language TEXT NOT NULL, metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)), revision INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS episodes(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), episode_number INTEGER NOT NULL, title TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(project_id, episode_number));
CREATE TABLE IF NOT EXISTS script_scenes(id TEXT PRIMARY KEY, episode_id TEXT NOT NULL REFERENCES episodes(id), order_index INTEGER NOT NULL, scene_number TEXT NOT NULL, heading_json TEXT NOT NULL CHECK(json_valid(heading_json)), blocks_json TEXT NOT NULL CHECK(json_valid(blocks_json)), revision INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS segments(id TEXT PRIMARY KEY, episode_id TEXT NOT NULL REFERENCES episodes(id), code TEXT NOT NULL, order_index INTEGER NOT NULL, title TEXT NOT NULL, source_scene_ids_json TEXT NOT NULL CHECK(json_valid(source_scene_ids_json)), target_duration_seconds REAL, revision INTEGER NOT NULL DEFAULT 0, UNIQUE(episode_id, code));
CREATE TABLE IF NOT EXISTS shots(id TEXT PRIMARY KEY, segment_id TEXT NOT NULL REFERENCES segments(id), order_index INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'active', revision INTEGER NOT NULL DEFAULT 0, duration_seconds REAL NOT NULL CHECK(duration_seconds > 0), shot_size TEXT NOT NULL, camera_angle TEXT NOT NULL, camera_movement TEXT NOT NULL, dialogue TEXT, sound TEXT, start_boundary_json TEXT NOT NULL CHECK(json_valid(start_boundary_json)), end_boundary_json TEXT NOT NULL CHECK(json_valid(end_boundary_json)), source_block_ids_json TEXT NOT NULL CHECK(json_valid(source_block_ids_json)));
CREATE TABLE IF NOT EXISTS shot_versions(id TEXT PRIMARY KEY, shot_id TEXT NOT NULL REFERENCES shots(id), revision INTEGER NOT NULL, content_json TEXT NOT NULL CHECK(json_valid(content_json)), source_changeset_id TEXT, created_at TEXT NOT NULL, UNIQUE(shot_id, revision));
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), kind TEXT NOT NULL, name TEXT NOT NULL, current_version_id TEXT, revision INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS asset_versions(id TEXT PRIMARY KEY, asset_id TEXT NOT NULL REFERENCES assets(id), version_number INTEGER NOT NULL, content_json TEXT NOT NULL CHECK(json_valid(content_json)), supersedes_id TEXT REFERENCES asset_versions(id), created_at TEXT NOT NULL, UNIQUE(asset_id, version_number));
CREATE TABLE IF NOT EXISTS reference_bindings(id TEXT PRIMARY KEY, shot_id TEXT NOT NULL REFERENCES shots(id), asset_id TEXT NOT NULL REFERENCES assets(id), asset_version_id TEXT NOT NULL REFERENCES asset_versions(id), usage TEXT NOT NULL, binding_mode TEXT NOT NULL CHECK(binding_mode IN ('frozen','follow_latest')), is_stale INTEGER NOT NULL DEFAULT 0, stale_reason TEXT, UNIQUE(shot_id, asset_id, usage));
CREATE TABLE IF NOT EXISTS prompt_versions(id TEXT PRIMARY KEY, owner_type TEXT NOT NULL, owner_id TEXT NOT NULL, kind TEXT NOT NULL, version_number INTEGER NOT NULL, content TEXT NOT NULL, negative_content TEXT, is_current INTEGER NOT NULL DEFAULT 1, source_changeset_id TEXT, created_at TEXT NOT NULL, UNIQUE(owner_type, owner_id, kind, version_number));
CREATE TABLE IF NOT EXISTS media_versions(id TEXT PRIMARY KEY, owner_type TEXT NOT NULL, owner_id TEXT NOT NULL, kind TEXT NOT NULL, storage_path TEXT NOT NULL, sha256 TEXT NOT NULL, mime TEXT NOT NULL, width INTEGER, height INTEGER, duration_seconds REAL, is_current INTEGER NOT NULL DEFAULT 1, is_stale INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS surface_contexts(session_id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), episode_id TEXT, segment_id TEXT, route TEXT NOT NULL, selected_shot_ids_json TEXT NOT NULL CHECK(json_valid(selected_shot_ids_json)), updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), capability TEXT NOT NULL, intent TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS task_snapshots(task_id TEXT PRIMARY KEY REFERENCES tasks(id), selection_json TEXT NOT NULL CHECK(json_valid(selection_json)), expected_revisions_json TEXT NOT NULL CHECK(json_valid(expected_revisions_json)), skill_manifest_json TEXT NOT NULL CHECK(json_valid(skill_manifest_json)), created_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS task_snapshots_immutable_update BEFORE UPDATE ON task_snapshots BEGIN SELECT RAISE(ABORT, 'task snapshot is immutable'); END;
CREATE TRIGGER IF NOT EXISTS task_snapshots_immutable_delete BEFORE DELETE ON task_snapshots BEGIN SELECT RAISE(ABORT, 'task snapshot is immutable'); END;
CREATE TABLE IF NOT EXISTS agent_runs(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), status TEXT NOT NULL, skill_name TEXT NOT NULL, skill_version TEXT NOT NULL, skill_hash TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT, error_json TEXT CHECK(error_json IS NULL OR json_valid(error_json)));
CREATE TABLE IF NOT EXISTS agent_run_events(run_id TEXT NOT NULL REFERENCES agent_runs(id), sequence INTEGER NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), created_at TEXT NOT NULL, PRIMARY KEY(run_id, sequence));
CREATE TABLE IF NOT EXISTS changesets(id TEXT PRIMARY KEY, task_id TEXT NOT NULL REFERENCES tasks(id), run_id TEXT REFERENCES agent_runs(id), project_id TEXT NOT NULL REFERENCES projects(id), status TEXT NOT NULL, base_revisions_json TEXT NOT NULL CHECK(json_valid(base_revisions_json)), summary TEXT NOT NULL, validated_fingerprint TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS changeset_operations(changeset_id TEXT NOT NULL REFERENCES changesets(id), ordinal INTEGER NOT NULL, op TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT, expected_revision INTEGER, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), PRIMARY KEY(changeset_id, ordinal));
CREATE TABLE IF NOT EXISTS changeset_impacts(changeset_id TEXT NOT NULL REFERENCES changesets(id), entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, impact_type TEXT NOT NULL, severity TEXT NOT NULL, detail_json TEXT NOT NULL CHECK(json_valid(detail_json)));
CREATE TABLE IF NOT EXISTS changeset_warnings(changeset_id TEXT NOT NULL REFERENCES changesets(id), code TEXT NOT NULL, severity TEXT NOT NULL, message TEXT NOT NULL, detail_json TEXT NOT NULL CHECK(json_valid(detail_json)));
CREATE TABLE IF NOT EXISTS domain_events(id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT NOT NULL REFERENCES projects(id), aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL, revision INTEGER NOT NULL, event_type TEXT NOT NULL, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), causation_id TEXT, correlation_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS generation_jobs(id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), owner_type TEXT NOT NULL, owner_id TEXT NOT NULL, kind TEXT NOT NULL, state TEXT NOT NULL, spec_json TEXT NOT NULL CHECK(json_valid(spec_json)), fingerprint TEXT NOT NULL, input_hashes_json TEXT NOT NULL CHECK(json_valid(input_hashes_json)), adapter TEXT NOT NULL, supersedes_job_id TEXT REFERENCES generation_jobs(id), confirmation_token_hash TEXT, confirmation_used INTEGER NOT NULL DEFAULT 0, error_json TEXT CHECK(error_json IS NULL OR json_valid(error_json)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);

INSERT OR IGNORE INTO schema_migrations(version, applied_at) VALUES (1, strftime('%Y-%m-%dT%H:%M:%fZ','now'));
